# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=2)),
                ('approval', models.CharField(max_length=2)),
                ('requested_time', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_has_sitting_on_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('time_schedule', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='doctor_has_sitting_on_location',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.location'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sitting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Doctor_has_sitting_on_location'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
