# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='location',
            name='time_schedule',
        ),
        migrations.AddField(
            model_name='location',
            name='time_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='time_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending Approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor_has_sitting_on_location',
            name='end_date',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
