# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20170708_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='requested_time',
        ),
        migrations.RemoveField(
            model_name='doctor_has_sitting_on_location',
            name='start_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='requested_date',
            field=models.CharField(default='Fri', max_length=20),
        ),
    ]
