# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20170709_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='location',
            name='time_start',
        ),
        migrations.AddField(
            model_name='location',
            name='day',
            field=models.CharField(default='Fri', max_length=20),
        ),
    ]
