# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20170709_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='requested_date',
        ),
    ]
