# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=2)),
                ('contact_no', models.CharField(max_length=20)),
                ('BMDC_reg_no', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=2)),
                ('contact_no', models.CharField(max_length=20)),
                ('guardian', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
                ('contact_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
