# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='doctor',
            name='app_time_per_patient',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
