# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170708_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_no',
            field=models.CharField(default='012', max_length=20),
        ),
    ]
