# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170708_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.CharField(default='N/A', max_length=30, null=True),
        ),
    ]
