# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170709_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='logged_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='logged_in',
            field=models.IntegerField(default=0),
        ),
    ]
