# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170709_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(default='50', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='app_time_per_patient',
            field=models.CharField(default='20', max_length=20),
        ),
    ]
